# Generated by Django 5.0.6 on 2024-07-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
    ]
