# Generated by Django 5.0.6 on 2024-07-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_remove_register_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='phonenumber',
        ),
    ]
