# Generated by Django 5.0.6 on 2024-11-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_remove_register_phonenumber'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='bgmi',
        ),
    ]
