# Generated by Django 5.0.6 on 2024-11-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0004_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='game',
        ),
    ]
